# Generated by Django 4.0.6 on 2022-08-21 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Slug', models.SlugField()),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Slug', models.SlugField()),
                ('Description', models.TextField()),
                ('Price', models.IntegerField()),
                ('Image', models.ImageField(upload_to='uploades/')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.category')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.company')),
            ],
            options={
                'ordering': ('-Created_at',),
            },
        ),
    ]
