# Generated by Django 4.0.6 on 2022-08-29 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
        ('userapp', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=35)),
                ('Phone', models.CharField(max_length=15)),
                ('Place', models.CharField(max_length=35)),
                ('Pincode', models.IntegerField(max_length=8)),
                ('Address', models.TextField()),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.product')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
            ],
        ),
    ]
