# Generated by Django 4.0.6 on 2022-08-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Pincode',
            field=models.IntegerField(),
        ),
    ]
